# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pIgaX-ZxzBFq5E_ClvRDu14vfPaMfnx8
"""

import keras as ks

import numpy as np

import scipy as sp

import gensim as gs

